Metflix/Metflix/urls.py
from django.contrib import admin
from django.urls import path, include

# Add Media Url to the urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('movies.urls')),
    path('movie_admin/', include('movie_admin.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Metflix/movie_admin/urls.py
# Movie_admin URL Conf
#========================


from . import views

from django.urls import path

app_name = 'movie_admin'
urlpatterns = [
	path('', views.index, name='index'),
    path('add_movies', views.add_movies, name='add_movies'),
	path('add_series', views.add_series, name='add_series'),
]

Metflix/movies/urls.py
# Movies URL conf
#========================


from . import views

from django.urls import path

app_name = 'movies'
urlpatterns = [
	path('', views.index, name='index'),
    path('episodes/<int:movie_id>/', views.episode_select, name='epsisode_select'),
    path('<int:movie_id>/', views.media_player, name='media_player'),
    path('<int:movie_id>/<int:season>/<int:episode>/', views.series_player, name = 'series_player'),

]

Metflix/movie_admin/models.py
from django.db import models

# Create your models here.

Metflix/movies/models.py
from django.db import models

# Create your models here.



class Movie(models.Model):
    title = models.CharField(max_length= 200)
    type = models.IntegerField() #Type 1 = Movie 2 = Series

    def __str__(self):
        return self.title


class Genre(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Genre_targets(models.Model):
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete = models.CASCADE)

    def __str__(self):
        return self.movie.title, self.genre.name


class Episode(models.Model):
    series = models.ForeignKey(Movie, on_delete= models.CASCADE)
    season = models.IntegerField()
    episode = models.IntegerField()
    path = models.CharField(max_length = 20)

Metflix/movie_admin/views.py
#==== MOVIE ADMIN VIEWS ====

from django.shortcuts import render, get_object_or_404

from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate

from movies.models import *

from Metflix.settings import MEDIA_ROOT, MEDIA_URL
import os

# Create your views here.

def index(request):
    print (MEDIA_ROOT[0])
    print (MEDIA_ROOT[1])
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    
    context = {
        'test': 'test'
    }

    return render(request, 'movie_admin/index.html', context)

def add_movies(request):
    MOVIE_ROOT = os.path.join(os.path.join(MEDIA_ROOT[0], MEDIA_ROOT[1]), 'movies')

    # Check movie root dir for new movie folders
    # and adds them to database
    movie_list_dirs = os.listdir(MOVIE_ROOT)
    for movie in movie_list_dirs:
        # Check if movie alredy is in database
        # if so do not add movie
        try: 
            movie_db = Movie.objects.get(title = movie)
        except:
            m = Movie.objects.create(title = movie, type = 1)
            m.save()
        else:
            print ('Movie excists')

    # Check al database entrys to the movie root dir 
    # if there is not dir with movie name 
    # Delete from database
    movie_list_db = Movie.objects.all()
    for movie in movie_list_db:
        if not os.path.isdir(os.path.join(MOVIE_ROOT, movie.title)):
            movie.delete()

    return HttpResponseRedirect(reverse('movie_admin:index'))

def add_series(request):

    SERIES_ROOT = os.path.join(MEDIA_ROOT, 'series')


    series_list_dir = os.listdir(SERIES_ROOT)

    for series in series_list_dir:
        
        try:
            series_db = Movie.objects.get(title = series)
        except:
            s = Movie.objects.create(title = movie, type = 2)
            s.save()
        else:
            print("Series Excists")

        # Search the series dir for season dirs
        season_list_dir = os.listdir(os.path.join(SERIES_ROOT, series))

        for season in season_list_dir:
            
            episode_db = Episode.objects.all()
            season_db = episode_db.filter()

    return HttpResponseRedirect(reverse('movie_admin:index'))

Metflix/movies/views.py
#==== MOVIE VIEWS ====

from django.shortcuts import render, get_object_or_404

from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate

from movies.models import *

# Create your views here.

from Metflix.settings import MEDIA_ROOT, MEDIA_URL
import os

def index(request):
    
    movies = Movie.objects.all()
    genres = Genre.objects.all()


    context = {
        'movies': movies,
        'genres': genres
    }

    return render(request, 'movies/index.html', context)

def episode_select(request, id):
    pass

def media_player(request, movie_id):
    
    movie = get_object_or_404(Movie, pk=movie_id)

    for f in os.listdir(os.path.join(MEDIA_ROOT[0], MEDIA_ROOT[1]) + '/movies/' + movie.title ):
        if f.endswith('.' + 'mp4'):
            movie_url = movie.title +'/' + f
        else:
            movie_url = 'No video file'
    
    movie_url = MEDIA_URL + movie_url

    context = {
        'movie_url': movie_url,
        'movie': movie,
    }

    return render(request, 'movies/media_player.html', context)


def series_player(request, movie_id, season, episode):
    pass

    context = {
        'test': 'Test'
    }
    return render(request, 'movies/media_player.html', context)

Metflix/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css" />

    <!-- Select2 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>


    <script src="{% static 'search.js' %}"></script>

    <meta charset="utf-8">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
    <main>
        {% include 'menu.html' %}
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

Metflix/templates/menu.html
<div class="sidenav">
    <a href="{% url 'movies:index' %}">Media</a><br />
    <a href="{% url 'movie_admin:index' %}">Admin</a><br />
    <br />
    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

Metflix/templates/movie_admin/index.html
<!-- templates/movie_admin/index.html -->
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class='container'>

    <a href="{% url 'movie_admin:add_movies' %}" style="color: black;">Add movies in dirr</a>

</div>




{% endblock %}

Metflix/templates/movies/index.html
<!-- templates/movies/index.html -->
{% extends 'base.html' %}
{% block content %}
{% load static %}


<div class="container">
    <h1>MittFlix</h1>


    <form method="get">
        <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Search here" />
        <button class="btn" type="submit" name="action">Search</button>
    </form>

    <table>
        <tr>
            <th>Title</th>
            <th>Type</th>
        </tr>
        {% for m in movies %}
        {% if m.type == 1 %}
        <tr onclick="clickLink(this)" data-href="{% url 'movies:media_player' m.id %}">
        {% else %}    
        <tr onclick="clickLink(this)" data-href="{% url 'movies:episode_select' m.id %}">
        {% endif %}
            <td>{{ m.title }}</td>
            <td>{{ m.type }}</td>
        </tr>
        {% endfor %}
    </table>


    <!-- Pagination buttons -->
    {% if customers.has_other_pages %}
    <div class="pagination flex">
        {% if customers.has_previous %}
        <a href="?page={{ customers.previous_page_number }}{% if search %}{{ search  }}{% endif %}">
            <div>&laquo;</div>
        </a>
        {% else %}
        <div class="disabled"><span>&laquo;</span></div>
        {% endif %}
        {% for i in customers.paginator.page_range %}
        {% if customers.number == i %}
        <div class="active"><span>{{ i }} <span class="sr-only"></span></span></div>
        {% else %}
        <a href="?page={{ i }}{% if search %}{{ search  }}{% endif %}"><div>{{ i }}</div></a>
        {% endif %}
        {% endfor %}

        {% if customers.has_next %}
        <a href="?page={{ customers.next_page_number }}{% if search %}{{ search  }}{% endif %}">
            <div>&raquo;</div>
        </a>
        {% else %}
        <div class="disabled"><span>&raquo;</span></div>
        {% endif %}
    </div>
    {% endif %}

</div>
{% endblock %}

Metflix/templates/movies/media_player.html
<!-- templates/movies/media_player.html -->
{% extends 'base.html' %}
{% block content %}
{% load static %}


<div class="container">
<video controls>
	
	<source src="{{ movie_url }}" type="video/mp4">

</video>
</div>



{% endblock %}